#pragma once
// phong lighting
namespace AA
{
const char* lit_vert_src =
"#version 330 core\n"
"layout(location=0)in vec3 inPos;\n"
"layout(location=1)in vec2 inTexUV;\n"
"layout(location=2)in vec3 inNorm;\n"
"out vec3 pass_Pos;\n"
"out vec2 pass_TexUV;\n"
"out vec3 pass_Norm;\n"
"uniform mat4 projection;\n"
"uniform mat4 model;\n"
"uniform mat4 view;\n"
"void main(){	\n"
"  pass_Pos = (model * vec4(inPos,1.)).xyz;\n"
"  pass_TexUV = inTexUV;\n"
"  pass_Norm = inNorm;\n"
"  gl_Position = projection * view * model * vec4(inPos,1);\n"
"}\n";

const char* lit_frag_src =
"#version 430																							\n"
"in vec3 pass_Pos;																						\n"
"in vec2 pass_TexUV;																					\n"
"in vec3 pass_Norm;																						\n"
"out vec3 out_Color;																					\n"
"struct Material {																						\n"
"    sampler2D Albedo;																					\n"
"    vec3 Specular;																						\n"
"    float Shininess;																					\n"
"};																										\n"
"struct DirectionalLight {																				\n"
"    vec3 Direction;																					\n"
"    vec3 Ambient;																						\n"
"    vec3 Diffuse;																						\n"
"    vec3 Specular;																						\n"
"};																										\n"
"struct PointLight {																					\n"
"    vec3 Position;																						\n"
"    float Constant, Linear, Quadratic;																	\n"
"    vec3 Ambient, Diffuse, Specular;																	\n"
"};																										\n"
"struct SpotLight {																						\n"
"    vec3 Position, Direction;																			\n"
"    float CutOff, OuterCutOff;																			\n"
"    float Constant, Linear, Quadratic;																	\n"
"    vec3 Ambient, Diffuse, Specular;																	\n"
"};																										\n"
"const int MAXPOINTLIGHTS = 50;																			\n"
"const int MAXSPOTLIGHTS = 25;																			\n"
"uniform vec3 viewPos;																					\n"
"uniform Material material;																				\n"
"uniform DirectionalLight directionalLight;																\n"
"uniform PointLight pointLight[MAXPOINTLIGHTS];															\n"
"uniform SpotLight spotLight[MAXSPOTLIGHTS];															\n"
"uniform int NUM_POINT_LIGHTS;																			\n"
"uniform int NUM_SPOT_LIGHTS;																			\n"
"vec3 CalcDirectionalLight(vec3 normal, vec3 viewDir);													\n"
"vec3 CalcPointLight(PointLight light, vec3 normal, vec3 viewDir);										\n"
"vec3 CalcSpotLight(SpotLight light, vec3 normal, vec3 viewDir);										\n"
"int i = 0;																								\n"
"void main() {																							\n"
"    vec3 result;																						\n"
"    vec3 normal = normalize(pass_Norm);																\n"
"    vec3 viewDir = normalize(viewPos - pass_Pos);														\n"
"    result += CalcDirectionalLight(normal, viewDir);													\n"
"    for (i = 0; i < NUM_POINT_LIGHTS; i++)																\n"
"        result += CalcPointLight(pointLight[i], normal, viewDir);										\n"
"    for (i = 0; i < NUM_SPOT_LIGHTS; i++)																\n"
"        result += CalcSpotLight(spotLight[i], normal, viewDir);										\n"
"    out_Color = result;																				\n"
"}																										\n"
"vec3 CalcDirectionalLight(vec3 normal, vec3 viewDir) {													\n"
"    vec3 lightDir = normalize(-directionalLight.Direction);											\n"
"    float diff = max(dot(normal, lightDir), 0.);														\n"
"    vec3 reflectDir = reflect(-lightDir, normal);														\n"
"    float spec = pow(max(dot(viewDir, reflectDir), 0.), material.Shininess);							\n"
"    vec3 ambient = directionalLight.Ambient * texture(material.Albedo, pass_TexUV).rgb;				\n"
"    vec3 diffuse = directionalLight.Diffuse * diff * texture(material.Albedo, pass_TexUV).rgb;			\n"
"    vec3 specular = directionalLight.Specular * spec * material.Specular;								\n"
"    return(ambient + diffuse + specular);																\n"
"}																										\n"
"vec3 CalcPointLight(PointLight light, vec3 normal, vec3 viewDir) {										\n"
"    vec3 lightDir = normalize(light.Position - pass_Pos);												\n"
"    float diff = max(dot(normal, lightDir), 0.0);														\n"
"    vec3 reflectDir = reflect(-lightDir, normal);														\n"
"    float spec = pow(max(dot(viewDir, reflectDir), 0.0), material.Shininess);							\n"
"    float dist = length(light.Position - pass_Pos);													\n"
"    float attenuation = 1.0 / (light.Constant + light.Linear * dist + light.Quadratic * (dist * dist));\n"
"    vec3 ambient = light.Ambient * texture(material.Albedo, pass_TexUV).rgb;							\n"
"    vec3 diffuse = light.Diffuse * diff * texture(material.Albedo, pass_TexUV).rgb;					\n"
"    vec3 specular = light.Specular * spec * material.Specular;											\n"
"    ambient *= attenuation;																			\n"
"    diffuse *= attenuation;																			\n"
"    specular *= attenuation;																			\n"
"    return (ambient + diffuse + specular);																\n"
"}																										\n"
"vec3 CalcSpotLight(SpotLight light, vec3 normal, vec3 viewDir) {										\n"
"    vec3 lightDir = normalize(light.Position - pass_Pos);												\n"
"    float diff = max(dot(normal, lightDir), 0.0);														\n"
"    vec3 reflectDir = reflect(-lightDir, normal);														\n"
"    float spec = pow(max(dot(viewDir, reflectDir), 0.0), material.Shininess);							\n"
"    float dist = length(light.Position - pass_Pos);													\n"
"    float attenuation = 1.0 / (light.Constant + light.Linear * dist + light.Quadratic * (dist * dist));\n"
"    float theta = dot(lightDir, normalize(-light.Direction));											\n"
"    float epsilon = light.CutOff - light.OuterCutOff;													\n"
"    float intensity = clamp((theta - light.OuterCutOff) / epsilon, 0.0, 1.0);							\n"
"    vec3 ambient = light.Ambient * texture(material.Albedo, pass_TexUV).rgb;							\n"
"    vec3 diffuse = light.Diffuse * diff * texture(material.Albedo, pass_TexUV).rgb;					\n"
"    vec3 specular = light.Specular * spec * material.Specular;											\n"
"    ambient *= attenuation * intensity;																\n"
"    diffuse *= attenuation * intensity;																\n"
"    specular *= attenuation * intensity;																\n"
"    return (ambient + diffuse + specular);																\n"
"}\n";
} // end namespace AA